# .streamlit/secrets.toml
DB_HOST = "pg-b523e2c-dvnspavan-6de7.h.aivencloud.com"
DB_USER = "avnadmin"
DB_PASS = "AVNS_ppSMWQeDdNmiwKuUt7D"
DB_NAME = "defaultdb"
DB_PORT = 5432  # PostgreSQL uses 5432, NOT 3306
